# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /post/:title
relative_permalinks: false

# Setup
title:               ABCDEFG
tagline:             'HIJKLMNOP'
description:         'ABCDEFGHIJKLMNOPQRSTUVWXYZ <a href="https://github.com/noasly">깃허브</a>'
url:                 https://noasly.github.io/
baseurl:             ''
paginate:            5

# About/contact
#author:
#  name:              Mark Otto
#  url:               https://twitter.com/mdo
#  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0

# Gems
plugins: [jekyll-paginate]